// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config'
import { defineConfig } from 'prisma/config'

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations'
  },
  datasource: {
    url: process.env['DATABASE_URL']
  },
  // Les occupations sont importées depuis `prisma/data/occupations.json` par
  // un script dédié (simulation par défaut, `--apply` pour écrire) plutôt que
  // par `prisma db seed` : il purge les tables et ne doit pas partir tout seul.
  //   npx tsx prisma/import-occupations.ts [--apply]
  seed: {
    run: 'echo "Utiliser: npx tsx prisma/import-occupations.ts [--apply]" && exit 1'
  }
})
